# sc-DMAE Configuration

# Path parameters
paths:
  data_path: /content/drive/MyDrive/Dataset/SingleCell/
  results_path: /content/drive/MyDrive/SingleCell/results/
  save_path: /content/drive/MyDrive/SingleCell/checkpoints/
  
# Dataset parameters
dataset:
  dataset: 10X_PBMC
  data_dim: 1000
  n_classes: 4

# Training parameters
training:
  batch_size: 256
  epochs: 100
  learning_rate: 1.0e-3
  hidden_size: 128
  dropout: 0.3
  masked_weights: 0.75
  num_workers: 4
  
# Model options
model:
  CNN: false
  UWL: true